# Generated by Django 5.0.4 on 2024-04-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_name',
            new_name='phone',
        ),
    ]
